version: '3'
services:
    confluence:
        image: "atlassian/confluence-server:7.2.0"
        volumes:
            - ./atlassian-agent.jar:/var/atlassian/atlassian-agent.jar
            - ./mysql-connector-java-5.1.49.jar:/opt/atlassian/confluence/confluence/WEB-INF/lib/mysql-connector-java-5.1.49.jar
            - ./confluence:/var/atlassian/application-data/confluence
        environment:
            - JAVA_OPTS="-javaagent:/var/atlassian/atlassian-agent.jar"
            - JVM_MINIMUM_MEMORY=2048m
            - JVM_MAXIMUM_MEMORY=4096m
            - JVM_RESERVED_CODE_CACHE_SIZE=512m
        ports:
            - "8090:8090"
            - "8091:8091"
        restart: always

